# Generated by Django 4.2.13 on 2024-09-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pugnere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_creer_produit', models.BooleanField(default=False)),
                ('peut_creer_service', models.BooleanField(default=False)),
                ('peut_enregistrer_vente', models.BooleanField(default=True)),
                ('peut_enregistrer_depense', models.BooleanField(default=False)),
                ('peut_creer_facture', models.BooleanField(default=False)),
                ('peut_telecharger_pdf', models.BooleanField(default=False)),
                ('peut_consulter_bilan', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
