# Generated by Django 4.2.13 on 2024-09-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pugnere', '0002_habilitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='salaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
