# Generated by Django 4.2.13 on 2024-09-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pugnere', '0003_employe_salaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalairePaye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pugnere.employe')),
            ],
        ),
    ]
